# Generated by Django 2.2 on 2020-03-10 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databasePracticeApp', '0002_auto_20200310_1300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wizard',
        ),
    ]
