# Generated by Django 2.2 on 2020-03-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databasePracticeApp', '0005_auto_20200310_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.CharField(default='old dojo', max_length=255),
            preserve_default=False,
        ),
    ]
