# Generated by Django 2.2 on 2020-03-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databasePracticeApp', '0007_authors_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='authors',
        ),
        migrations.DeleteModel(
            name='books',
        ),
    ]
