# Generated by Django 2.2 on 2020-03-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksAuthorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.CharField(default='Notes Here', max_length=45),
            preserve_default=False,
        ),
    ]
