# Generated by Django 2.2 on 2020-03-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_title', models.CharField(max_length=45)),
                ('show_network', models.CharField(max_length=15)),
                ('show_desc', models.CharField(max_length=1999)),
            ],
        ),
    ]
